name: "Web Build"

on:
  push:
    branches:
      - guide

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@main
      
    - name: Download
      run: npm i vue-discord-message@5.0.2 vuepress@1.8.2 vuepress-theme-hope@latest @mr-hope/vuepress-plugin-copy-code@1.19.1 @mr-hope/vuepress-plugin-feed@1.19.1 @mr-hope/vuepress-plugin-reading-time@1.19.1

    - name: Build
      run: npm run build

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.ACCESS_TOKEN }}
        publish_dir: ./guide/.vuepress/dist
        publish_branch: gh-pages
        destination_dir: ./guide/
